### ISSUE TITLE
bug: Home margin overflow

### ISSUE THREAD

**Issue by Chever-John** [Chever-John/JohnChever-Blog#3]
## Description

Home margin overflow

## Reproduce

Visit the [website](https://www.cheverjohn.xyz/) and you will see.

## Environment

Chrom: Version 102.0.5005.115 (Official Build) (arm64)

**Comment by uniqie** [comment]
Remove unnecessary spaces

**Comment by Chever-John** [comment]
@uniqie Thanks for pointing out this problem.
Can you create a PR to fix this for me?

**Comment by uniqie** [comment]
Yes

**Comment by uniqie** [comment]
@Chever-John Yes
